### ISSUE TITLE
About Kill PM

### ISSUE THREAD

**Issue by thienha1** [JMBQ/Honkai_Impact_3rd_menu_mod#12]
I saw that u edit 2 days ago and just add KillPM() method to kill signature verification, and i tried this for another game that is KOF Allstar by Netmarble
Here: https://play.google.com/store/apps/details?id=com.netmarble.kofg&hl=vi&gl=US
I applied your method before but almost this game still detected this package has been tampered somehow...Can you join with me to find out how to bypass that type signature verification?

**Comment by thienha1** [comment]
After mod apk, a notice will show after press start login like this...
Demo:
![vri4azsvzjf71](https://user-images.githubusercontent.com/18132856/219691775-ce79f606-ce26-4bfd-bcb4-4a7003f82cee.jpg)

**Comment by JMBQ** [comment]
It has no signature checksum, I don't make any changes, re-sign and the game works fine.
There is a dex check, it's so weak that I just put my own code into a new dex and bypasses it.

like this:
https://mega.nz/file/AxtiVSJB#sndZ6LNLyPX3cf-7n3lZ9L3_gdw3U1o8Na-X966HFpo

**Comment by thienha1** [comment]
I didnt know that this game has Dex check, i tried with my mod with your methods and still got this error
![Screenshot_2023-02-18-20-15-17-260_com netmarble kofg](https://user-images.githubusercontent.com/18132856/219867970-234852ce-5850-4c4d-b7ae-7bece3a3f6cb.jpg)
Hmm, another integrity verification?

**Comment by JMBQ** [comment]
Download my modified apk and study it

https://mega.nz/file/AxtiVSJB#sndZ6LNLyPX3cf-7n3lZ9L3_gdw3U1o8Na-X966HFpo

**Comment by thienha1** [comment]
> Download my modified apk and study it
> 
> https://mega.nz/file/AxtiVSJB#sndZ6LNLyPX3cf-7n3lZ9L3_gdw3U1o8Na-X966HFpo

It seem obfuscated, how to learn from this?
![Capture](https://user-images.githubusercontent.com/18132856/221423184-b5564f4a-31d2-43fa-a68b-ef640a416bb2.PNG)

**Comment by thienha1** [comment]
> Download my modified apk and study it
> 
> https://mega.nz/file/AxtiVSJB#sndZ6LNLyPX3cf-7n3lZ9L3_gdw3U1o8Na-X966HFpo

It seem obfuscated, how to learn from this?
![Capture](https://user-images.githubusercontent.com/18132856/221423184-b5564f4a-31d2-43fa-a68b-ef640a416bb2.PNG)

**Comment by JMBQ** [comment]
> > Download my modified apk and study it
> > https://mega.nz/file/AxtiVSJB#sndZ6LNLyPX3cf-7n3lZ9L3_gdw3U1o8Na-X966HFpo
> 
> It seem obfuscated, how to learn from this? ![Capture](https://user-images.githubusercontent.com/18132856/221423184-b5564f4a-31d2-43fa-a68b-ef640a416bb2.PNG)

Its code is irrelevant and you can get the source code from PmsHook.java.
As long as nothing has changed in the dex, then naturally the dex detection will not detect it

**Comment by thienha1** [comment]
> > > Download my modified apk and study it
> > > https://mega.nz/file/AxtiVSJB#sndZ6LNLyPX3cf-7n3lZ9L3_gdw3U1o8Na-X966HFpo
> > 
> > 
> > It seem obfuscated, how to learn from this? ![Capture](https://user-images.githubusercontent.com/18132856/221423184-b5564f4a-31d2-43fa-a68b-ef640a416bb2.PNG)
> 
> Its code is irrelevant and you can get the source code from PmsHook.java. As long as nothing has changed in the dex, then naturally the dex detection will not detect it

Ok but the source code from https://github.com/JMBQ/Honkai-Impact-3-mod/blob/main/app/src/main/java/com/android/support/PmsHook.java seem different than PmsHook.java in classes4.dex, can you share original source code PmsHook.java that u did before as you posted at MEGA? And how to get signature to make fake signature?

**Comment by JMBQ** [comment]
you need this   https://mega.nz/file/J4cg3RYb#qwMkscaK2MQerR4RR_7IDpS_dl8r69oTFFWO_JhXkzg

Decompile it and you'll see it clearly.

killPM() is a static method, just call it directly, but you need to get the sign string yourself
```
public class PmsHook extends Application {
    static {
        killPM();
    }
   ...
}
```

**Comment by thienha1** [comment]
> you need this https://mega.nz/file/J4cg3RYb#qwMkscaK2MQerR4RR_7IDpS_dl8r69oTFFWO_JhXkzg
> 
> Decompile it and you'll see it clearly.
> 
> killPM() is a static method, just call it directly, but you need to get the sign string yourself
> 
> ```
> public class PmsHook extends Application {
>     static {
>         killPM();
>     }
>    ...
> }
> ```

Ok i know that you need me get the sign myself but i really dunno how to get it? And also i dont see any KillPM() methods when complied dex to smali in your apk latest version!!
![Capture](https://user-images.githubusercontent.com/18132856/222763717-70b57feb-3d13-4d9e-8474-4c968879b48a.PNG)

**Comment by JMBQ** [comment]
> > you need this https://mega.nz/file/J4cg3RYb#qwMkscaK2MQerR4RR_7IDpS_dl8r69oTFFWO_JhXkzg
> > 
> > Decompile it and you'll see it clearly.
> > 
> > killPM() is a static method, just call it directly, but you need to get the sign string yourself
> > 
> > ```
> > public class PmsHook extends Application {
> >     static {
> >         killPM();
> >     }
> >    ...
> > }
> > ```
> 
> Ok i know that you need me get the sign myself but i really dunno how to get it? And also i dont see any KillPM() methods when complied dex to smali in your apk latest version!!
> ![Capture](https://user-images.githubusercontent.com/18132856/222763717-70b57feb-3d13-4d9e-8474-4c968879b48a.PNG)

toast has already told you, you just firmly believe that the game has signature verification

**Comment by thienha1** [comment]
ok this KOF Allstar game dont have signature verification, so what about another game that has xigncode anticheat like BlueArchive?
Here: https://play.google.com/store/apps/details?id=com.YostarJP.BlueArchive&hl=vi&gl=US
And still following your method before then got detected by Xigncode

![Screenshot_2023-03-05-09-42-00-521_com YostarJP BlueArchive](https://user-images.githubusercontent.com/18132856/222938989-17616f5e-e973-462c-a895-97179d1427ad.jpg)

**Comment by JMBQ** [comment]
> ok this KOF Allstar game dont have signature verification, so what about another game that has xigncode anticheat like BlueArchive?
> Here: https://play.google.com/store/apps/details?id=com.YostarJP.BlueArchive&hl=vi&gl=US
> And still following your method before then got detected by Xigncode
> 
> ![Screenshot_2023-03-05-09-42-00-521_com YostarJP BlueArchive](https://user-images.githubusercontent.com/18132856/222938989-17616f5e-e973-462c-a895-97179d1427ad.jpg)
> 

Just kill xigncode, I can’t log in to the game because of IP lock, so I can’t verify whether it can be played normally

**Comment by thienha1** [comment]
> > ok this KOF Allstar game dont have signature verification, so what about another game that has xigncode anticheat like BlueArchive?
> > Here: https://play.google.com/store/apps/details?id=com.YostarJP.BlueArchive&hl=vi&gl=US
> > And still following your method before then got detected by Xigncode
> > ![Screenshot_2023-03-05-09-42-00-521_com YostarJP BlueArchive](https://user-images.githubusercontent.com/18132856/222938989-17616f5e-e973-462c-a895-97179d1427ad.jpg)
> 
> Just kill xigncode, I can’t log in to the game because of IP lock, so I can’t verify whether it can be played normally

ok, i'll explore how to kill xigncode, you can find out which one trigger AC that change something in game original apk then sign and run the game then just wait to login screen weather AC trigger or not. No need to login into the game, AC activated when u start running this game
