### ISSUE TITLE
修改AndroidManifest.xml中的问题

### ISSUE THREAD

**Issue by sherlokcerry** [JMBQ/Honkai_Impact_3rd_menu_mod#23]
![image](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/117138559/587ba2dd-13cd-4440-93d3-165a56b5102f)
![image](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/117138559/ce6f6b14-c60f-4d5e-bbca-2b79d5004327)
如上图，SEA版本的apk在反编译后AndroidManifest.xml文件内的内容和您提供的流程图内容不完全一致，在进行修改时需要与示意图中的内容保持完全一致因而删掉几行代码吗？谢谢！

**Comment by JMBQ** [comment]
不需要你删，你只需要添加就行

**Comment by sherlokcerry** [comment]
> 不需要你删，你只需要添加就行

好的

**Comment by sherlokcerry** [comment]
能看到弹窗，在hoyoverse logo过后就闪退了，只有一次进入了检查配置更新，检查到3%就闪退了。检查了一下应用权限，悬浮窗权限，存储什么的都打开了。操作步骤是：
1.将反编译的AndroidManifest.xml打开，修改了其中的内容（添加两处内容，修改一处内容）；
2.编译，得到apk，用bandizip打开官方apk，复制出了class-class3.dex共三个文件，与1.4.0文件夹中class4.dex与asset文件夹一起复制到编译得到的apk中（以压缩文件形式打开，并添加文件）；
3.最后拖动编译后的apk到apkeasytool中，点击zipAlign，做下角出现sign successfully，打开2-Recompiled APKs将其中的apk传输给了移动设备进行安装。
运行游戏使用了加速器。
不明确是哪里出了问题，请教一下如何排查，谢谢！

**Comment by JMBQ** [comment]
只要能看到左上角悬浮图标，就不是操作问题

排查很简单，如果你这台手机可以正常运行官方6.6apk，那就代表你手机里有逆向工具触发了我的检测

**Comment by sherlokcerry** [comment]
使用你提供的直装包顺利的打开了游戏，看来是我操作上出了些问题
