### ISSUE TITLE
Video tutorial for installation

### ISSUE THREAD

**Issue by kaizer2121** [JMBQ/Honkai_Impact_3rd_menu_mod#24]
Getting confused mostly at this part. Do I need to extract the apk with winrar?

"Use a compression software (e.g. winrar) to open the official apk and extract all the dex from the first level directory. This step is to bypass the dex check, whether you have modified the smali file before or not, the dex file will change after packing, we need to restore this, star rail can also bypass dex check this way

Open P using the compression software and copy the extracted dex file into P along with the assets and classes4.dex I have given you. The name of the extracted dex should not be duplicated with the name of the dex I gave, if it is, change my dex to classes5.dex"

**Comment by JMBQ** [comment]
Use a compression software (e.g. winrar) to open the official apk and extract all the dex from the first level directory.  The dex needs to be extracted, but you can of course use other methods of extraction

**Comment by kaizer2121** [comment]
So I extract it like this? Move dex4 and assets folder from 1.4.0 release to the extracted folder, compile it back to apk, then zipalign with apkeasytool?

![image](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/134293641/f1f67b2c-2b47-4121-b573-c0883167efed)

**Comment by JMBQ** [comment]
i will upload video, wait

**Comment by kaizer2121** [comment]
Thank you, I have been doing it wrong all the time
