### ISSUE TITLE
SEA Version error 

### ISSUE THREAD

**Issue by RinKovalskia** [JMBQ/Honkai_Impact_3rd_menu_mod#26]
SEA Version error "Unofficial version detected. Please download game from official site or app store" how do I fix it? Thank You !

**Comment by RinKovalskia** [comment]
i downloaded the apk in folder patched_apk from mega

**Comment by JMBQ** [comment]
What is the Android version of your phone

**Comment by tuananhcn** [comment]
Having the same problem with Pocox3 pro unrooted android 12

**Comment by RinKovalskia** [comment]
> u need to hide root，The apk I provided can be played normally on my root phone

still not work :(

**Comment by JMBQ** [comment]
Did you see the menu?
Rin
tuan

**Comment by tuananhcn** [comment]
> Did you see the menu?
> Rin
> tuan

Yes, i did

**Comment by sherlokcerry** [comment]
我也遇到了同样的问题，显示非官方安装包，我的手机并没有root。

**Comment by JMBQ** [comment]
I uninstalled it after testing it on Monday, and today I reinstalled it, the prompt is unofficial, it is certain that the protection has been upgraded on the server side

**Comment by YIEngt** [comment]
> 查了下原因是之前其他平台发布的官方安装包他们不认可，强行作废了。又不是防护升级，这就有点不要脸了。我今晚会发布新的apk

大佬你好，你分享的6.6的修改文件是不是不适用与现在的6.6的安装包呀，我试着修改了繁中服和欧服都会闪退，原安装包都是官网最新的

**Comment by JMBQ** [comment]
> > 查了下原因是之前其他平台发布的官方安装包他们不认可，强行作废了。又不是防护升级，这就有点不要脸了。我今晚会发布新的apk
> 
> 大佬你好，你分享的6.6的修改文件是不是不适用与现在的6.6的安装包呀，我试着修改了繁中服和欧服都会闪退，原安装包都是官网最新的

查看 readme 进度
