### ISSUE TITLE
Not official version issue?

### ISSUE THREAD

**Issue by sean7119** [JMBQ/Honkai_Impact_3rd_menu_mod#27]
![Screenshot_20230524-222344977_1](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/116971236/bec4db9b-2cfe-4ba9-990d-12548dd5d9e4)
Have anyone occurred the same situation ? 
( 6.6 TW )

**Comment by Rempacious** [comment]
Pretty sure it's this https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/issues/26#issuecomment-1560664980

**Comment by JMBQ** [comment]
see the hack progress of readme
