### ISSUE TITLE
加载变慢

### ISSUE THREAD

**Issue by sherlokcerry** [JMBQ/Honkai_Impact_3rd_menu_mod#29]
感谢大佬重新回归更新，只是更新之后登陆、进入商店等操作，加载时间比之前的版本更长了，是游戏本身的问题吗，我没有下载原版游戏尝试？不知道其他人有没有遇到这样的问题。

**Comment by thienha1** [comment]
> 感谢大佬重新回归更新，只是更新之后登陆、进入商店等操作，加载时间比之前的版本更长了，是游戏本身的问题吗，我没有下载原版游戏尝试？不知道其他人有没有遇到这样的问题。

Same issue man, after update connection become slower than older version, although my internet high speed, low ping but this maybe something block host from client

**Comment by JMBQ** [comment]
global?

**Comment by sherlokcerry** [comment]
> global?

playing the SEA ver

**Comment by JMBQ** [comment]
更长是多长？具体点，我都没碰上

**Comment by sherlokcerry** [comment]
> 更长是多长？具体点，我都没碰上

一分钟以上有时更久，就像是死机的感觉，游戏画面静止不动，开始游戏，进入商城、女武神界面都会这样。

**Comment by JMBQ** [comment]
https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/78288131/2fe74446-0208-4542-8ea1-38cfc50ee4a5

这就是SEA 6.7.0 
我没发现你所说的问题

**Comment by sherlokcerry** [comment]
[](url)

https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/117138559/9f8340ba-f336-4010-a6cd-de4a4ebcd23a
录了个屏，设备和网络都没有变化，新版本有这个问题

**Comment by JMBQ** [comment]
6.8.0再看看

**Comment by sherlokcerry** [comment]
> 6.8.0再看看

SEA ver 6.8.0 没有上个版本的加载缓慢的情况了，感谢！
