### ISSUE TITLE
Obfuscation function name

### ISSUE THREAD

**Issue by thienha1** [JMBQ/Honkai_Impact_3rd_menu_mod#31]
miHoYo start Obfuscate function name in HI3 that make me spend a lot of time to find out true function, so sad bruh :((

**Comment by JMBQ** [comment]
yeah, My response is to target by feature code so as not to bother with obfuscation

**Comment by thienha1** [comment]
> yeah, My response is to target by feature code so as not to bother with obfuscation

So how to look & find out that make it work? Using IDA or somethime?

**Comment by JMBQ** [comment]
IDA or c/c++ source code

**Comment by JMBQ** [comment]
> > IDA or c/c++ source code
> 
> But it seen il2cpp has been encrypted long time ago, and u still look good for true function? How? IDA take a lot of time to analysis this file....

The official will hide the api of il2cpp in 6.9.0, it may not be possible to make dump.cs at that time, IDA is always a reliable partner

**Comment by thienha1** [comment]
> > > IDA or c/c++ source code
> > 
> > 
> > But it seen il2cpp has been encrypted long time ago, and u still look good for true function? How? IDA take a lot of time to analysis this file....
> 
> The official will hide the api of il2cpp in 6.9.0, it may not be possible to make dump.cs at that time, IDA is always a reliable partner

Yeah, i tried and got nothing from game
![Screenshot_2023-08-22-18-52-16-863_com dp logcatapp](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/d757dde1-fc28-4b97-89f3-cc7b6b5da243)
This il2cpp API has been hided as u said..

**Comment by thienha1** [comment]
> > > IDA or c/c++ source code
> > 
> > 
> > But it seen il2cpp has been encrypted long time ago, and u still look good for true function? How? IDA take a lot of time to analysis this file....
> 
> The official will hide the api of il2cpp in 6.9.0, it may not be possible to make dump.cs at that time, IDA is always a reliable partner

I hope they wont apply in SEA version, otherwise I dunno what to do next....

**Comment by thienha1** [comment]
What I got in libunity....hmm they change something there!!
![Screenshot 2023-08-24 212610](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/b0574359-0973-4d80-95dc-ce5c6ed73063)

**Comment by JMBQ** [comment]
> What I got in libunity....hmm they change something there!!
> ![Screenshot 2023-08-24 212610](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/b0574359-0973-4d80-95dc-ce5c6ed73063)
> 

Yes, this is how unity gets the api, this method is actually inside libil2cpp.so, and it's particularly obscure.  When the SEA version is updated, the api will definitely be hidden

**Comment by thienha1** [comment]
> > What I got in libunity....hmm they change something there!!
> > ![Screenshot 2023-08-24 212610](https://user-images.githubusercontent.com/18132856/263005011-b0574359-0973-4d80-95dc-ce5c6ed73063.png)
> 
> Yes, this is how unity gets the api, this method is actually inside libil2cpp.so, and it's particularly obscure. When the SEA version is updated, the api will definitely be hidden

So sad, do you have solution for 6.9 update in the future?

**Comment by JMBQ** [comment]
As mentioned in the previous reply, IDA directly searches for the target method. No matter what tricks the official plays, the target method always exists, just find it.

**Comment by thienha1** [comment]
> As mentioned in the previous reply, IDA directly searches for the target method. No matter what tricks the official plays, the target method always exists, just find it.

So how to get begin? I tried your method in https://github.com/JMBQ/dump-games/blob/main/进击的手游01：月圆之夜.md and I dont see this method like this
![02](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/1cbd7e26-90ad-499a-a66d-d63c6a10cb84)

**Comment by JMBQ** [comment]
I mean using ida to directly find the sub_xxx where the cheat function is located

**Comment by thienha1** [comment]
You mean I have to find new offset of cheat function in libil2cpp.so at IDA and without dump? That's ok but it take a lot of time to find out true offset of cheat functions.. 
![Screenshot 2023-08-29 185310](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/dae71acd-b77e-49f5-92ef-d41ae8d23c94)
This file has more than 70k functions..
Also, we can find out another way to dump file and search text then ez to offset as we want like as your post before:
https://github.com/JMBQ/dump-games/tree/main
And since your GitHub created, you always search offset of functions like open file in IDA then read each function sub_XXXX?

**Comment by thienha1** [comment]
> 

I tried this solution and got nothing like this thing:
![833877_9NU88K4U88XCDUC](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/47419beb-6c36-4d54-ab17-e02ad6ce2028)
Reality:
![Screenshot 2023-08-29 185310](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/74798fc6-8048-410b-a58b-1d0bd2201694)
"Once you have the previous version of cheat offsets", you mean if I have offsets in the old version then I has looking for HEX value in new version and compare to old version to determine new offset position?

**Comment by thienha1** [comment]
Hope you can find out something that can be dump!!
