### ISSUE TITLE
Find il2cpp API offset in custom libil2cpp

### ISSUE THREAD

**Issue by thienha1** [JMBQ/Honkai_Impact_3rd_menu_mod#38]
I tried this solution and got nothing like this thing:
![833877_9NU88K4U88XCDUC](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/47419beb-6c36-4d54-ab17-e02ad6ce2028)
Reality:
![Screenshot 2023-08-29 185310](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/74798fc6-8048-410b-a58b-1d0bd2201694)
"Once you have the previous version of cheat offsets", you mean if I have offsets in the old version then I has looking for HEX value in new version and compare to old version to determine new offset position?

**Comment by JMBQ** [comment]
This involves the calling and calling of the old method, as well as the logic of the method itself. For example, I can locate the offset of the new method in ida through these associations.

**Comment by thienha1** [comment]
"These associations" mean looking logic in new method itself? This is what I can understand as u said, example:
I have old offset with this function
![Screenshot 2023-09-10 222339](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/74b7bf9c-9707-4e77-96c8-aa0d8b90cd4f)
Then looking into IDA by jump to old offset 
![Screenshot 2023-09-10 222843](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/02dd93bc-162a-4744-bdaf-ce41ca3edb53)
And find offset of new method like that?
![Screenshot 2023-09-10 223344](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/60760c56-34ad-4e51-b0b2-b610c67e042b)

**Comment by JMBQ** [comment]
No, you don't really understand what I'm saying. I think maybe only a complete and very detailed tutorial can make you understand.

**Comment by JMBQ** [comment]
For example, in the mov w8, #0x34b8 in your picture, you may be able to find a new offset by searching for 0x34b8 in the new version, but it is not absolute. This value may also change in the new version. This is just one of the ways.

**Comment by JMBQ** [comment]
The offset obtained in dump.cs is the actual memory offset. If you put it in ida, you need to perform a quantitative offset calculation on it.  For example, 0xa103368, it may be one of the three 0xa104368, 0xa102368, 0xa103368 in ida

**Comment by JMBQ** [comment]
but it is not absolute

**Comment by thienha1** [comment]
Yeah they arent the same!
Ver 6.8 SEA:
![Screenshot 2023-09-12 194254](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/48cf1b2f-384c-4411-bc86-8761e1b2bbc1)
Ver 6.9 CN:
![Screenshot 2023-09-12 194331](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/664c27cc-2819-4e99-9416-444b22f69719)
And a result in CN version, seem different...
![Screenshot 2023-09-12 194504](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/d93af0a2-1683-4e24-80d6-28d48cdd1193)

**Comment by JMBQ** [comment]
com.miHoYo.enterprise.NGHSoD   v6.9.0

这是由代码自动打印出来的API偏移，稍微核对了几个，都对，并没有全部核对
别找我要名称，我还没打印

a6696c0
cbcd3a0
cbcd3a8
cbcd530
cbcd65c
5d2a380
cbcdb74
5d2a8cc
cbcdfd0
cbce040
cbce0b0
cbce1e4
932b680
a8fa83c
9d2d73c
989c1f8
9c56bc8
9c56c9c
9c569d8
9c56a44
a036a98
a036ba8
a036c84
b549ba0
b549c70
5d2a328
a2beaa0
a2beb60
5d2a3c8
a2e3500
a2e3338
a2e3560
a2e3404
a2e27e4
5d2a6a4
5d2a310
a2e29f8
9e5de70
989bf48
989c03c
97e8818
9d51204
9c5f084
9c5efa8
9c5edbc
97e8990
9c5fb60
9c5fa88
9c5f890
9b690b0
93186bc
98bf504
9b653fc
9b346e8
9a424a4
a5bd428
9a686a4
b53b31c
9d1a164
a8ed2e8
9d50984
a044554
b54ade8
5d2a398
a2eb844
a332f80
a55b09c
a55b1e0
a55b028
5d2a6f0
a55b03c
a55b1d4
a0a3544
a0a34bc
a0a34c0
a0a35ec
a0a35f0
a0a3604
5d2a714
986eb30
cefe0b4
cefe0bc
cefe0c4
cefe100
cefe1fc
cefe3f8
cefe4f0
cefe754
cefe840
cefe974
5d2a780
c6fcc14
c6fcc1c
c6fcc24
5d2a0f8
c6fcc70
c6fcd6c
c6fcfec
c6fd0e4
c6fd3cc
c6fd4b8
c6fd660
c6fd748
cbcd380
cbcd388
cbcd390
cbcd398
a388b4c
a388b5c
a388ee8
5d2a94c
9dc4f2c
9dc4f3c
5d2a624
9dc534c
a84b8fc
a84b90c
a84bd10
a84bd40
5d2aa1c
a47a88c
a47acbc
5d2a2cc
caed588
caed598
caed7a8
caed7d4
b26aee4
b26aef4
5d2a2a0
b26b2a8
b39a090
b39a0a0
5d2ac14
b39a4b4
c4249f0
c424a00
c424e08
c424e38
caf5440
caf5450
caf5884
caf58b8
a6b9570
5d2a3e4
5d2a744
a6b9a10
a26c750
a26c760
a26cbf0
a26cc28
a84c8a8
a84c8b8
a84cd6c
a84cda4
a5ff17c
a5ff18c
5d2a608
a5ff67c
caf58d4
caf58e4
caf5d44
caf5d78
ced8404
ced8414
ced88a8
ced88e0
c7a1078
c7a1088
c7a1540
c7a1578
c7a1594
c7a15a4
c7a1a5c
c7a1a98
d018dc4
d018dd4
d0191b8
d0191e8
cd22aa0
cd22ab0
cd22e40
cd22e64
cb1b14c
cb1b15c
cb1b4f0
5d2a020
97e7c88
9ff7ef0
5d2a830
9ff7f00
9ff8140
9ff8268
9ff859c
5d2a738
9ff7cd8
9ff7d78
9ff7f08
9ff7f44
9ff810c
5d2a2f8
9ff84cc
9ff8534
5d2aa20
9ff8734
9ff879c
9ff88b8
9ff8978
5d2ab70
9ff8bc0
a55c5e0
a55c6d4
a55c55c
5d2a71c
a55c72c
a55c73c
ced2048
ced2058
ced2438
ced2468
cbcc87c
cbccba8
cbcc870
cbcc8c4
cbccb00
cbccbb0
986ba58
cba0f74
9d274e8
9d27620
9b77c08
9d5b4a0
9866ab0
9866b88
c6fb2d4
c6fb2e4
c6fb674
5d2a8a8
d03e634
d03e644
d03e854
d03e880
5d2a918
caf5ed8
caf5d94
5d2aa24
caf5e64
caf5e74
caf5f28
caf5fb4
c424e54
c42519c
c425484
c4256d8
c425808
c4258bc
c425efc
c425fd0
c426038
c42636c
5d2a698
c426444
5d2a9b4
d48dfb0
5d2a5c8
5d2a6e8
d1cb91c
df62828
df62830
df6281c
d03f9c0
d03fa0c
d03fa2c
d03f888
d03f924
d03fa50
5d2a010
9d27bbc
d4ad348
d4ad318
d4ad3dc
d1cb6cc
d1cb6d4
5d2a278
d1cb6e4
5d2a844
d4ad64c
d4ad5bc
d4ad670
d4ad8b8
9d27cb8
9796990
d040914
d0409dc
5d2a880
d03fb40
d03fbcc
d03fc98
d03fde8
d03ff14
d040024
d040164
5d29fd8
d040534
d0407f4
d040894
d0409e4
5d2a964
d040ad8
d040b80
d040be4
d040d44
d040d90
5d2ac60
c6fbeac
c6fc074
c6fc088
cefdfb4
cefe054
986dfbc
c6fb6e4
c6fb7e8
c6fba98
c6fbce8
c6fb6b4
986d800
986d544
986d23c
5d2aa4c
986da00
986db84
9d2e934
a2ed3c0
a2ed074
a2ed0cc
d1f7648
d1f7638
a2ef0f8
d1f7644
a2ee9f4
a2eec1c
d1f77ac
d1f79b8
d1f7a48
d1f7ca4
d1f7f0c
986ccd0
d03f734
d03f72c
d03f750
d03f760
d03f770
d03f690
d03f720
cefddb8
cefddac
5d2a120
cefdde8
cefddfc
9d27758
cefcc84
5d2a250
cefcd4c
5d2ab88
cefcf78
cefd338
cefd620
cefd89c
cefdb78
d8aaef8
d8aaf08
d8ab298
d8ab2bc
9b72f84
9d279dc
5d2ab5c
5d2a9a0
b54f964
ba73108
ba731e4
ba732bc
ba7445c
ba745f4
ba745fc
ba74e14
ba74eec
5d2a8d4
ba751f0
ba73028
ba734b0
ba73688
ba73790
ba73870
5d2ac58
ba73a2c
ba73b08
ba73d04
ba73f00
ba740ec
ba741c4
ba742a4
ba7437c
ba7452c
ba7471c
ba75370
ba756a4
ba75854
ba75a00
ba75cfc
ba75f6c
c0fd9ac
c0fda88
c0fded8
c0fdee0
c0fdfb8
c0fe0c4
c0fe0cc
c0fe8e4
c0fe8ec
c0fe8f4
c0fe9cc
5d2abec
c0fdb60
c0fdc40
5d2a704
5d2a740
c0fdfc0
5d2a0bc
5d2a76c
5d2a014
5d2a578
c0fdffc
c0fe1ec
c0fe9d4
c0fe9f0
c0fe9f8
c0fea90
c0fec40
c0fedec
c0fedf4
c0fedfc
a2834d8
a2835e4
a2838a4
a283ee0
a283f44
a28420c
5d2ab74
a284a10
a284a18
a284c38
5d2ab78
5d2ab84
a285598
a2855a0
a28600c
a280e50
a280fc8
a2810f8
a281414
a2815f4
a2816e8
a2817e8
a281d68
a281f34
a282168
a282450
a282734
a2828b8
a2829c4
a282c20
a282d08
a2837c0
a283830
a283a08
a283aac
a283d7c
a283e78
a283fa8
a2840d0
a284214
5d2a6cc
a2843dc
a284768
5d2ac40
a284a7c
a285184
a28561c
5d2a640
a285fec
a286010
5d2a080
5d2a7dc
a286358
a28677c
5d2a07c
a105fcc
a6148d8
a6142b4
a6144a0
a6145ac
a6146b4
a614248
a61475c
a614814
9de12bc
9de1330
9de1148
9de1178
9de117c
9de12c8
a860874
a86087c
a860d4c
a860598
a8606d0
a8608f8
a8609d4
a861030
a861120
a8612fc
a8616d4
a8617a0
a8618ec
a8619c8
a861ad8
a861b94
a861e60
a861f2c
5d2a73c
9ff8eb8
5d2a038
5d2a018
9ff8f94
9ff916c
a4916cc
a49173c
a491264
a491294
a491298
5d2a368
9d3cf68
5d2a684
b59bcc8
b59bcd0
b59bcc0
b59bcd8
b48a3a0
b48a780
b48a930
5d2a9dc
b48accc
5d2a6f4
5d2a620
b48aef4
5d2a444
5d2a458
b48b940
b48bb68
5d2a134
bfb47fc
bfb4a1c
5d2abc8
bfb4e30
bfb4ec0
bfb4f9c
bfb5348
5d2a5b4
bfb59b8
5d2a148
5d2a10c
b2b065c
b2b0664
5d2a030
b2b076c
b2b0864
b2b095c
5d2a69c
b2b0b60
b2b33a4
5d2ab8c
b2b3a74
b2b3afc
b2b3b04
5d2a408
b2b3b70
b2b3bd4
5d2a46c
b2afb24
b2afbbc
5d2abc4
b2afcf4
5d2aa04
b2afee0
b2b0564
5d2a58c
b2b0c30
b2b0d14
b2b0e74
5d2a2b4
b2b10ec
b2b114c
b2b12f0
5d2a210
5d2a4dc
b2b167c
5d2a8ec
b2b1c1c
b2b1d7c
b2b2450
b2b2a78
b2b2b3c
5d2ab38
5d2a034
b2b3334
b2b33ac
b2b3410
5d2a0a8
b2b4148
b2b4250
b2b4634
b2b47ac
b2b4874
b91464c
b91465c
b9149fc
5d2a894
b914c64
b91446c
b914498
b914658
b91494c
b4520bc
b452120
b452874
b45287c
b451db8
b451e60
b451ed4
b452128
b45219c
b452210
b45226c
b4522e0
5d2a41c
b452460
b79ebe8
b79ebf0
b79ea70
b79ea98
b79ea9c
b79eca0
b9861dc
b986240
b986994
b98699c
5d2a1d4
b985f80
5d2a944
b986248
b9862bc
b986330
b9863a4
b986400
b9864c0
b986580
5d2a6b8
b3e38ec
b3e376c
b3e3794
b3e3798
b3e399c
c1732dc
c173448
c1739b0
c173bf4
b47c2a8
b47c3ac
b47c41c
b47c458
b69faa8
b69fb48
b69fbb8
b69fbf4
c1d294c
c1d2ab8
5d2a564
5d2a224
c1d3604
5d2a978
5d2a8ac
c1d6280
c1d62b0
c1d6458
c1d65f0
5d2a2e4
5d2a03c
ba0b7d0
5d2aa60
5d2a5a0
5d2a550
ba0ba14
ba0ba84
5d2a7c8
ba4be04
ba4be24
ba4bfb4
ba4bfbc
ba4bfc4
ba4bfcc
5d2a8c4
5d2aba8
ba4c064
ba4c0a0
5d2a9f0
ba4c22c
ba4b51c
ba4b600
ba4b75c
ba4c114
ba4c490
ba4c5b4
ba4c814
5d2a094
ba4c950
ba4ca30
ba4cb38
ba4cc4c
ba4cc90
5d2a6f8
9328ab0
ba4cfe4
ba4d03c
ba4d148
5d2a5e4
5d2a238
ba4d270
5d2a7f0
5d29fc0
ba4d6d8
ba4d740
ba4d89c
ba4d9b0
ba4da18
ba4db8c
ba4dd40
ba4ddb0
ba4de70
ba4df30
5d2a804
ba4e108
ba4e34c
ba4e49c
5d2a54c
ba4ed1c
ba4edf4
5d2ab80
5d2ac68
ba4f2e8
ba4f3c4
5d2ab7c
ba4f5a0
5d2a98c
5d2a724
ba4f8a0
ba4f938
ba4f9d0
ba4fa80
ba4fb98
b48105c
b481064
b480ec8
b480ef4
b480ef8
b481000
5d2ac5c
9b69208
9d57c44
bb0cae8
bb0caf0
bb0caf8
5d2a01c
bb0e1c4
bb0e1cc
5d2a8d0
bb0cab8
bb0cb18
5d2a798
bb0cd18
bb0ceb4
5d2a670
bb0d11c
bb0d29c
bb0d380
5d2ab90
bb0d49c
bb0d6a8
bb0d778
bb0d7ec
bb0d8d8
bb0d994
bb0da1c
bb0daec
bb0dcc8
bb0df04
bb0df4c
bb0df7c
bb0e024
bb0e0ec
bb0e254
5d2a28c
b59bf64
b59bf6c
b59bec8
b59befc
b59c074
b59c1bc
b59c270
b59c274
b59c2dc
b2deb60
b2deb9c
b2debd8
b2debe0
b2deb20
b2debe8
b8f1e74
b8f1e7c
b8f1e84
b8f1b40
b8f1c48
b8f1d64
b8f1f0c
b8f1f78
b8f2218
b8f2334
b8f23a4
5d2ab28
b8f2524
b8f2660
b8f273c
b8f2884
b8f2a3c
b8f2b38
b8f2b6c
bd15ac8
bd15c44
5d2a6a0
bd15984
bd15994
bd15bb4
bd15cbc
b6ab184
b6ab18c
b6ab324
b6ab5e0
b6ab644
b6ab73c
b6ab7a0
b6ab898
b6ac4a8
5d2a054
b6ac4b8
b6ac51c
b6ac580
b6ac6d0
b6ad278
b6ad280
b6aac08
b6aac9c
b6aae40
b6aaea4
b6ab020
5d2abac
5d2a950
b6aba60
b6abb74
b6abf8c
b6abff0
b6ac068
b6ac130
b6ac264
b6ac3e0
b6aca88
b6ace40
5d2ab10
b6ad088
b6ad150
5d2a3d0
b602ff0
b603060
b6031a8
5d2a1a4
b603988
b603bac
b602e40
b602f18
b602f80
b6030c8
b603138
be91c60
be91cc4
5d2a81c
5d2a66c
be9101c
be910c4
be9113c
be91200
be912c4
be91668
be91ccc
be91d40
be91db4
be91e10
bb5fd54
5d2a948
bb5fbe8
bb5fc7c
bb5fcec
bb5fff0
b77c1d8
b77c1ec
5d2ac54
bd65cfc
bd65d10
bb60e08
bb60e6c
bb6102c
bb61034
bb601c4
bb6026c
5d2a24c
bb603a8
bb6046c
bb60810
5d2ac64
bb60ee8
bb60f5c
bb60fb8
bd66100
bd661c4
bd65f94
bd66028
5d2a7b0
5d2a6e0
b8f3258
b8f326c
b77c298
c073a80
c073a94
b8f305c
5d2a70c
5d2a15c
b6a94e4
5d2ac2c
bb5fa54
bea93c0
5d2a858
bea94fc
bea95ac
bea0200
bea057c
bea08f4
5d2a050
bea0960
bea09c4
bea0a28
bea0a8c
bea0af0
bea0d54
5d2a8c8
bea0d64
bea0d6c
bea0d74
bea1e30
bea1f34
bea20b8
bea2248
be9ef8c
be9f198
5d2ac70
be9f3d0
be9f4a4
be9f540
be9fce0
be9fe68
be9ff14
5d2a264
5d2a3c0
bea0b54
bea0c54
bea0dfc
bea0e44
bea0fbc
5d2a5e0
bea10b8
bea1344
bea18c4
bea1948
bea1a2c
bea1af4
bea1bbc
bea1c84
bea1d4c
bea25f4
bea26dc
bea2744
bea28b0
bea2978
bea2ad0
bea2b84
bea2d30
b22a0f0
b22a3c8
b22a4e8
b22a56c
b22a784
b22a0b8
b22a0e4
b22a1f8
b22a88c
b7800d0
5d2a6fc
b77ff18
b77ff54
5d2a174
b7801c0
be964e8
be964f0
be96330
be9636c
be96378
be965d8
b8f3434
b8f3454
b8f345c
b8f3464
b8f38d8
b8f3930
b8f3404
b8f3530
b8f35a4
b8f3618
5d2a354
b8f36dc
b8f3864
b8f39a4
b8f3a80
b8f3b5c
b8f3c7c
b8f3cf0
c3f39cc
c3f39ec
c3f39f4
c3f39fc
c3f3e70
c3f3ec8
c3f399c
c3f3ac8
c3f3b3c
c3f3bb0
c3f3c0c
c3f3c74
c3f3dfc
c3f3f3c
c3f4018
c3f40f4
c3f418c
5d2aa18
bd19ae4
bd19b1c
5d2a3ac
bd19b2c
bd19628
bd19694
bd19714
bd19744
bd19bb4
bd19bb8
bd19bc0
5d2a1fc
bd19c44
bd1a1f8
bd1a224
5d2a628
bd1a924
bd1a954
bd1a9f4
bd1ad6c
cb7b5cc
cb7b640
cb7b72c
5d2a18c
cb7ba84
cb7baf8
cb7bd90
cb7bf40
cb7bf50
cb7bf74
cb7c200
cb7c224
cb7c5a8
bea6d54
bea6d5c
bea6d64
bea6d6c
bea6d74
bea6d7c
bea6d84
5d2a658
bea6d94
bea6df4
bea6e54
bea70bc
bea6b74
bea6c08
5d2a068
bea72c8
bea7318
bea7370
bea74c0
bea75a4
5d2a0e4
bea7a28
bea7b08
bea7c80
bea7d60
bea7ed8
bea8098
c0e2090
c0e210c
c0e21f8
c0e1510
c0e1584
c0e17f8
c0e1860
c0e18c8
c0e1bdc
c0e208c
c0e2208
c0e2374
c0e23e4
5d2a9c8
c773918
ba12244
b35eea0
b35eeb4
c0e3468
c0e3478
5d29fcc
c0e3830
c3ffa38
c3ffa40
c3ffa48
c3ff738
c3ff840
c3ff95c
c3ffad0
c3ffb08
5d2a434
5d2ab04
c3ffe6c
c3fff2c
c3fffec
c4000c8
c4001b4
c400284
c400480
c07c1c0
c07c33c
5d2a0d0
c07c08c
c07c098
c07c2ac
c07c3b4
9fe098c
9fe099c
9fe0e60
9fe0ea4
a2659ac
a2659bc
a265e7c
a265ec0
5d2a1e8
a471324
a471800
a471848
a471854
a471864
a471d34
a471d7c
5d2a60c
a5f6f8c
a5f749c
5d2aa38
a78453c
a78454c
a784aa0
a784af4
a2000d0

**Comment by JMBQ** [comment]
Neither, I don’t need to manually analyze so, the c code I set will automatically find the memory offset for me.

**Comment by thienha1** [comment]
> Neither, I don’t need to manually analyze so, the c code I set will automatically find the memory offset for me.

Hmm, memory offset, u mean get inside game then find value in memory and get those offset?
