### ISSUE TITLE
SEA Version 

### ISSUE THREAD

**Issue by RJ-RJJ** [JMBQ/Honkai_Impact_3rd_menu_mod#41]
sir why no add one hit?

**Comment by JMBQ** [comment]
nice idea, So you've got the memory offset of one hit?

**Comment by MawMawLon** [comment]
Damage mod = insta ban

**Comment by RJ-RJJ** [comment]
i see, i only can use one hit with game guardian only :v but only my character, and cant use in story character

**Comment by tesun32** [comment]
> sir why no add one hit?

yes, im wait for ths too.
cant wait more features

**Comment by RJ-RJJ** [comment]
tq hope next new feature have one hit 😁
