### ISSUE TITLE
About Memory Offset 

### ISSUE THREAD

**Issue by thienha1** [JMBQ/Honkai_Impact_3rd_menu_mod#42]
About memory offset, u mean get inside game then find value in memory and get those offset? So I can use GameGuardian then get ingame and scan value to reach out new offset?

**Comment by JMBQ** [comment]
do it if u can

**Comment by thienha1** [comment]
> do it if u can

I tried it but it show only 
![Screenshot 2023-09-21 190334](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/18132856/3b0b555d-b3d7-448f-befe-e47ccc69e40e)
result!

**Comment by thienha1** [comment]
> do it if u can

can u show me your way that how to find new offset in the new version?

**Comment by JMBQ** [comment]
I've actually said what to do before, but you don't seem to have mastered it. So let's get some real hands-on training.
Take that no cd and practice, before first finding its offset via 6.8dump.cs, going to ida to locate it, and then looking for its unique code, and then looking for the new version of the method offset based on that code.
![123](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/78288131/21c3cc0e-b131-4559-928a-114ad93aa1a7)
You see, excluding the time of ida analysing the i64 file, it only took me 1 minute to grab the new version of the offset, the picture must be mosaic, if I tell you the answer directly it makes no sense, you have to learn to find it yourself!
