### ISSUE TITLE
Unofficial version detected. (SEA Version)

### ISSUE THREAD

**Issue by RJ-RJJ** [JMBQ/Honkai_Impact_3rd_menu_mod#43]
can update sir 🙏

**Comment by Kotabo** [comment]
sir 🙏🙏🙏

**Comment by tesun32** [comment]
cant wait update

**Comment by JMBQ** [comment]
This is caused by the official remote update of the defense strategy, which cannot be updated quickly. I recommend using URC to replace the menu module. You can use it even if your phone does not have root.

**Comment by RJ-RJJ** [comment]
> This is caused by the official remote update of the defense strategy, which cannot be updated quickly. I recommend using URC to replace the menu module. You can use it even if your phone does not have root.

i have root, before i try the URC but not work, that why i use mod apk, the urc i follow ur tutorial but whem run, nothing jappen like 3 stars too not work

**Comment by JMBQ** [comment]
> i have root, before i try the URC but not work, that why i use mod apk, the urc i follow ur tutorial but when run nothing happen like 3 stars too not work

You need to manually flash the 142 fixed mod. 

The information you provide is too little to locate the problem.  
I need screenshots of the homepage and logs, as well as screenshots of your magisk’s homepage

**Comment by RJ-RJJ** [comment]
> > i have root, before i try the URC but not work, that why i use mod apk, the urc i follow ur tutorial but when run nothing happen like 3 stars too not work
> 
> You need to manually flash the 142 fixed mod.
> 
> The information you provide is too little to locate the problem. I need screenshots of the homepage and logs, as well as screenshots of your magisk’s homepage

can i use h3 playstore?
