### ISSUE TITLE
楼主能制作中国服的崩坏三MOD吗

### ISSUE THREAD

**Issue by lingdang86** [JMBQ/Honkai_Impact_3rd_menu_mod#46]
目前没有ROOT的手机，希望作者能出一个中国服的崩坏三MOD，中国服现在7.1版本了。

**Comment by JMBQ** [comment]
能做，也不打算继续做简中
曾经在6.1-6.4做过，但没几个人用，浪费时间

**Comment by lingdang86** [comment]
> 能做，也不打算继续做简中 曾经在6.1-6.4一班，但没几个人用，浪费时间

那只能有一个可以root的手机自己安装了，非常感谢楼主。
