### ISSUE TITLE
About Split Apks

### ISSUE THREAD

**Issue by Zukamiri** [JMBQ/Honkai_Impact_3rd_menu_mod#48]
Do you know how to fix it?
![Screenshot_20240118_165539](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/111028318/24671542-36ea-44bc-8f71-ade09bae80fa)

**Comment by JMBQ** [comment]
update the android system version of your phone.
android 9 -> target api:30

**Comment by Zukamiri** [comment]
My phone uses Android 13

**Comment by JMBQ** [comment]
> My phone uses Android 13

ok，the reason i found, i will try to fix

**Comment by legnaraudevip** [comment]
Hola como puedo comprarte una versión vip ( necesito más velocidad )

**Comment by legnaraudevip** [comment]
Hello, how can I buy a VIP version from you (I need more speed) thank you, I will be attentive

**Comment by JMBQ** [comment]
> Hello, how can I buy a VIP version from you (I need more speed) thank you, I will be attentive 

In fact, you just need to change the characters. The increase in attack speed is not obvious for some characters.
