### ISSUE TITLE
DMG Muliplier

### ISSUE THREAD

**Issue by Schumilex5** [JMBQ/Honkai_Impact_3rd_menu_mod#49]
Hey, is it risky or possible to raise the damage multiplier from x2?

**Comment by JMBQ** [comment]
There are many ways to change damage-based features, and common changes are high risk, as bans have proven. 
There are also methods that won't get banned, but it can't be applied to multiple servers and require a lot of time to analyze the offsets for each server, It goes against my philosophy of making mods easily, so my mod should have no damage related features. 
URC's LK is a special damage feature that can be applied to all servers, so I added it, but it's still highly risky. 
I don't want users using my mod to get banned, so LK won't be in the mod either.

**Comment by Schumilex5** [comment]
Oh I think my english was bad there my apologies. I meant the attack speed.
Altho I suppose based on your ideals that might be a stretch too.
All cool tho I respect that and thanks for the reply.
