### ISSUE TITLE
Crash in Android 14

### ISSUE THREAD

**Issue by Rempacious** [JMBQ/Honkai_Impact_3rd_menu_mod#50]
Hello, some users seems to be experiencing random crashes in Android 14 when toggling on a mod feature during game. Here is a matlog provided by a user after the mod crashed.
[jbmqhi3.txt](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/files/14447908/jbmqhi3.txt)

**Comment by JMBQ** [comment]
02-29 13:14:19.110 F/DEBUG   (27608): backtrace:
02-29 13:14:19.110 F/DEBUG   (27608):       #00 pc 000000000008dcc4  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy_aarch64_simd+196) (BuildId: 02a91a85343debb2911714273ff2b670)
02-29 13:14:19.110 F/DEBUG   (27608):       #01 pc 0000000001c5384c  /data/app/~~IMud2TjMifS7hZ5wtDUwBQ==/com.miHoYo.bh3global-v7KHrcJUpCnNQONMerPcAw==/split_config.arm64_v8a.apk!libunity.so (offset 0x14f0b000) (BuildId: a0b33b00b497d260)
02-29 13:14:19.110 F/DEBUG   (27608):       #02 pc 00000000016b5994  /data/app/~~IMud2TjMifS7hZ5wtDUwBQ==/com.miHoYo.bh3global-v7KHrcJUpCnNQONMerPcAw==/split_config.arm64_v8a.apk!libunity.so (offset 0x14f0b000) (BuildId: a0b33b00b497d260)
02-29 13:14:19.110 F/DEBUG   (27608):       #03 pc 00000000016b6728  /data/app/~~IMud2TjMifS7hZ5wtDUwBQ==/com.miHoYo.bh3global-v7KHrcJUpCnNQONMerPcAw==/split_config.arm64_v8a.apk!libunity.so (offset 0x14f0b000) (BuildId: a0b33b00b497d260)
02-29 13:14:19.110 F/DEBUG   (27608):       #04 pc 00000000016adc34  /data/app/~~IMud2TjMifS7hZ5wtDUwBQ==/com.miHoYo.bh3global-v7KHrcJUpCnNQONMerPcAw==/split_config.arm64_v8a.apk!libunity.so (offset 0x14f0b000) (BuildId: a0b33b00b497d260)
02-29 13:14:19.110 F/DEBUG   (27608):       #05 pc 0000000001c5311c  /data/app/~~IMud2TjMifS7hZ5wtDUwBQ==/com.miHoYo.bh3global-v7KHrcJUpCnNQONMerPcAw==/split_config.arm64_v8a.apk!libunity.so (offset 0x14f0b000) (BuildId: a0b33b00b497d260)
02-29 13:14:19.110 F/DEBUG   (27608):       #06 pc 00000000000fd0f4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 02a91a85343debb2911714273ff2b670)
02-29 13:14:19.110 F/DEBUG   (27608):       #07 pc 0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 02a91a85343debb2911714273ff2b670)

It seems like some thread was started that caused the crash.
If the user
1. does it crash if you play straight through without the mod feature turned on?
2. turns on the mod feature, but doesn't turn it off halfway through, does it crash?
3. turns on the mod feature and closes it halfway through, does this crash?

**Comment by Rempacious** [comment]
1. It doesn't crash without any mod features enabled
2. It crashed after some seconds of play time or waiting for a bit
3. Same results with 2 after waiting some few seconds, it still crashes before or after closing a mod feature.

The crash seems to be random after waiting for some time toggling a mod usually less than 30 seconds

**Comment by JMBQ** [comment]
It may be that the hook framework is not suitable for Android 14 and you need to wait for the hook framework to be updated, which will take several months.
