### ISSUE TITLE
Game running in background unexpectedly with abnormal memory usage

### ISSUE THREAD

**Issue by Hikari35p** [JMBQ/Honkai_Impact_3rd_menu_mod#52]
Sometimes the game starts running on its own in the background (without me opening it). And if I play for more than 30 minutes, the memory usage goes crazy, reaching over 3GB of RAM, with peaks of 4GB+. Then my phone starts lagging and freezing, and I have to force restart it. with Mod turned off it also freezing my phone.
I'm running on Android 11 and using SEA apks

Note: This is not happening on the Original Apk from playstore 
![IMG_20240310_143841](https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/assets/121005267/142d95aa-5a43-4c44-ac2d-cb39f38674aa)

**Comment by JMBQ** [comment]
Great feedback, I really need this

1.  Will this also happen with 7.2.0?

2. When you run the official version of the game for more than 30 minutes, how much memory does the game use? It won’t cause a crash, right?

3. When you play games, do you frequently switch mods on and off, such as once every 5 minutes? I set it to perform 500 hooks every time it is turned on or off, so the game's running memory will continue to increase.

4. How many grams of memory does your entire mobile phone have?

5.  You said that the game will run automatically when the game is not actively running?  Really?  Oh my god, maybe you don’t know how much permissions this requires to do. Android 11 does not allow this to happen under normal circumstances, and I don’t bother to add such code. I can’t imagine any possibility.

**Comment by Hikari35p** [comment]
1. I don't play on V7.2.0 the last Version that I tried is V7.1.0 or V7.0.0 (I forgot) and this is not happened.

2. On the official/original it takes max at 2Gb, and yes, it's not crashed.

3. No, I only turned On once after login screen and never turn it off again.

4. I have 6GB of Ram.

5. Yes Imagine it too, there's no permission to make the game auto start, so I think it might be a bug. The game itself has a "notification" system, but perhaps it bugged out, so instead of sending notifications, it just launches the game on background, I'm not sure, I'm just guessing.

**Comment by Hikari35p** [comment]
> Great feedback, I really need this
> 
> 1.  Will this also happen with 7.2.0?
> 
> 2. When you run the official version of the game for more than 30 minutes, how much memory does the game use? It won’t cause a crash, right?
> 
> 3. When you play games, do you frequently switch mods on and off, such as once every 5 minutes? I set it to perform 500 hooks every time it is turned on or off, so the game's running memory will continue to increase.
> 
> 4. How many grams of memory does your entire mobile phone have?
> 
> 5.  You said that the game will run automatically when the game is not actively running?  Really?  Oh my god, maybe you don’t know how much permissions this requires to do. Android 11 does not allow this to happen under normal circumstances, and I don’t bother to add such code. I can’t imagine any possibility.

1. I don't play on V7.2.0 the last Version that I tried is V7.1.0 or V7.0.0 (I forgot) and this is not happened.

2. On the official/original it takes max at 2Gb, and yes, it's not crashed.

3. No, I only turned On once after login screen and never turn it off again.

4. I have 6GB of Ram.

5. Yes Imagine it too, there's no permission to make the game auto start, so I think it might be a bug. The game itself has a "notification" system, but perhaps it bugged out, so instead of sending notifications, it just launches the game on background, I'm not sure, I'm just guessing.

**Comment by JMBQ** [comment]
MEGA，ramless version, retry

**Comment by Hikari35p** [comment]
I'll try

**Comment by Hikari35p** [comment]
Fixed, no crash
Thank you
