### ISSUE TITLE
Direct loading requests an update

### ISSUE THREAD

**Issue by yjw6** [JMBQ/Honkai_Impact_3rd_menu_mod#60]
Is the big guy free to update the direct installation?,Now the game is updated.,The direct installation in June can't be used.,Trouble the big guy to update it quickly.qaq

**Comment by pneumonoultramicroscopicsilicovolcan** [comment]
It keeps telling me I need an update ![Screenshot_2024-07-29-19-07-33-04_b5a5c5cb02ca09c784c5d88160e2ec24.jpg](https://github.com/user-attachments/assets/b402160b-f4b2-4a1e-bc3c-0d7a79acc29e)
