### ISSUE TITLE
The first and fourth functions of the suspended window in the direct installation version have failed to turn on the prompt

### ISSUE THREAD

**Issue by yjw6** [JMBQ/Honkai_Impact_3rd_menu_mod#61]
The new version of the direct installation function floating window prompts failure to open the first and fourth functionsI hope the author can fix it

**Comment by JMBQ** [comment]
这是正常的
有多人将该mod搬运至淘宝咸鱼售卖，所以受到了限制

**Comment by yjw6** [comment]
好的谢谢

**Comment by pokemc32ryan** [comment]
> 所以

啥時候會再打開
