### ISSUE TITLE
卸載後換成原版會閃退

### ISSUE THREAD

**Issue by pokemc32ryan** [JMBQ/Honkai_Impact_3rd_menu_mod#62]
卸載後換成原版會閃退，換回來一樣會閃退
ROG phone1_8+128_s845

**Comment by pokemc32ryan** [comment]
只有換過的國際版會閃退，一樣的手機玩台版沒事，換之前也沒事

**Comment by JMBQ** [comment]
真是缺乏常识

举个例子，在安卓11以上的手机里，一旦卸载了拼多多，那么就算拼多多的工程师再怎么拽，拼多多也不可能岁土转生地跑来继续影响这台安卓手机

把无需root的直装mod卸载后，手机上发生的任何事都不再与直装mod有关

**Comment by pokemc32ryan** [comment]
可，實際情況就是這樣

**Comment by pokemc32ryan** [comment]
android9~

**Comment by pokemc32ryan** [comment]
> 真是缺乏常识
> 
> 举个例子，在安卓11以上的手机里，一旦卸载了拼多多，那么就算拼多多的工程师再怎么拽，拼多多也不可能岁土转生地跑来继续影响这台安卓手机
> 
> 把无需root的直装mod卸载后，手机上发生的任何事都不再与直装mod有关

不是我沒常識，我也知道基本不可能，但這就是我遇到的問題～

**Comment by JMBQ** [comment]
所以你需要去查找其他可能的原因，比如手机已root等等，我已经帮你排除了直装mod搞事的可能性了

**Comment by pokemc32ryan** [comment]
root隱藏了，他會在"connecting to network..."時閃退，沒開網路能活得好好的，一開就閃退
