### ISSUE TITLE
大佬这个源码可以加入自动更新吗？求加入

### ISSUE THREAD

**Issue by wwwww56** [JMBQ/Honkai_Impact_3rd_menu_mod#63]
就是bynamemodding那个。不想每次都修改基址

**Comment by JMBQ** [comment]
自己下载对应源码合并即可，都是cmakelist编译，非常简单

**Comment by wwwww56** [comment]
> 自己下载对应源码合并即可，都是cmakelist编译，非常简单

尝试过，但是没有生效，不知道哪里的问题，还请大佬出手
