### ISSUE TITLE
Mod gone forever?

### ISSUE THREAD

**Issue by pneumonoultramicroscopicsilicovolcan** [JMBQ/Honkai_Impact_3rd_menu_mod#65]
I see the thread is gone from the website, and the mod hasn't been updated. Does this mean this is it? Thank you for those months with the mod 🫡

**Comment by Rempacious** [comment]
I already planned to stop updating the other regions in the next version due to personal problems, just a coincidence. You can still update the mod https://github.com/JMBQ/Honkai_Impact_3rd_menu_mod/blob/main/HOW_TO_USE_PROJECT.md
