### ISSUE TITLE
Game crash when start

### ISSUE THREAD

**Issue by Quan838-cell** [JMBQ/Honkai_Impact_3rd_menu_mod#70]

**Comment by JMBQ** [comment]
You didn't provide any information, so I can only suggest you change the device

**Comment by Quan838-cell** [comment]
sorry my phone is redmi turbo 3 256+12gb

**Comment by pneumonoultramicroscopicsilicovolcan** [comment]
> android 14?

Yes, those are Android 14

**Comment by Quan838-cell** [comment]
yes android 14
