### ISSUE TITLE
error cannot open application

### ISSUE THREAD

**Issue by Tuanph1016** [JMBQ/Honkai_Impact_3rd_menu_mod#71]
when opening the app can't open it closes automatically tried many times iqoo neo 9s+ android 14 device

**Comment by JMBQ** [comment]
How did you install it? Did the previous version run successfully?

**Comment by Tuanph1016** [comment]
I use SAI 4.5 to install the previous version 7.7 I use it normally without the error of automatically closing when opening

**Comment by Tuanph1016** [comment]
Review

**Comment by Tuanph1016** [comment]
https://github.com/user-attachments/assets/b62dab14-8437-473a-8418-45e0aff5b3d1

**Comment by JMBQ** [comment]
rooted?

**Comment by Tuanph1016** [comment]
I use normal version 7.7 without root, why did you switch to root 🥺🥺🥺

**Comment by JMBQ** [comment]
> I use normal version 7.7 without root, why did you switch to root 🥺🥺🥺

No root is required. I just asked if your device is rooted. The reason is basically clear. Android 14 cannot adapt to the newly added detection code, resulting in a crash. This part of the code will be cancelled in subsequent versions.
