### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by Z-I-H-A-D** [JMBQ/Honkai_Impact_3rd_menu_mod#72]
Please update to 7.9.0

**Comment by pneumonoultramicroscopicsilicovolcan** [comment]
> Please update to 7.9.0 
> 

They JUST updated it after saying they were going to think about it, cut them some slack

**Comment by Z-I-H-A-D** [comment]
have to download 25gb again😓

**Comment by Z-I-H-A-D** [comment]
Update😫😫😫😫😫😫😫😫😫😫

**Comment by DeanwayCh** [comment]
Global already update, how about SEA?

**Comment by Z-I-H-A-D** [comment]
Both r updated....plz check whether game crash or not at startup

**Comment by JMBQ** [comment]
not crash on my devices

**Comment by Z-I-H-A-D** [comment]
💖
