### ISSUE TITLE
How to install mumu 12 player 64 bit?

### ISSUE THREAD

**Issue by SerjoHacks** [JMBQ/Honkai_Impact_3rd_menu_mod#74]
When I download the new version from the official website and install it. It installs Android 32 bit (86x). Where can I find and install the 64 bit version?

**Comment by JMBQ** [comment]
https://mumu.163.com/update/
![12](https://github.com/user-attachments/assets/b398197a-513d-4b39-8a9a-400122d74fba)

**Comment by SerjoHacks** [comment]
> https://mumu.163.com/update/ ![12](https://private-user-images.githubusercontent.com/78288131/393562016-b398197a-513d-4b39-8a9a-400122d74fba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjQzODAsIm5iZiI6MTczMzY2NDA4MCwicGF0aCI6Ii83ODI4ODEzMS8zOTM1NjIwMTYtYjM5ODE5N2EtNTEzZC00YjM5LThhOWEtNDAwMTIyZDc0ZmJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDEzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMGI5NDE3NzQ0MWZhNWRmMDI0ZmFkYWY5YTJlNjAxZmE0NDZiYTEyMzFmMDM1YmNmMDAyZjI2ZTlhMDI5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vq1aRvncTKjRa7I_1xF6dVYgS_2PzyBJkkrmq0DSXD8)

Worked, thank you!
